# Generated by Django 6.1 on 2026-08-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'انجام شده')], default='pending', max_length=20),
        ),
    ]
