# Generated by Django 6.1 on 2026-08-08 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mental_readiness', models.PositiveSmallIntegerField(choices=[(1, 'خیلی کم'), (2, 'کم'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')])),
                ('satisfaction', models.PositiveSmallIntegerField(choices=[(1, 'خیلی ناراضی'), (2, 'ناراضی'), (3, 'متوسط'), (4, 'راضی'), (5, 'خیلی راضی')])),
                ('focus_level', models.PositiveSmallIntegerField(choices=[(1, 'خیلی کم'), (2, 'کم'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')])),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'خیلی آسان'), (2, 'آسان'), (3, 'متوسط'), (4, 'سخت'), (5, 'خیلی سخت')])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='planner.studysession')),
            ],
        ),
    ]
