# Generated by Django 6.1 on 2026-08-12 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_studyfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfeedback',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی آسان'), (2, 'آسان'), (3, 'متوسط'), (4, 'سخت'), (5, 'خیلی سخت')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studyfeedback',
            name='focus_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی کم'), (2, 'کم'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studyfeedback',
            name='mental_readiness',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی کم'), (2, 'کم'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studyfeedback',
            name='satisfaction',
            field=models.PositiveSmallIntegerField(choices=[(1, 'خیلی ناراضی'), (2, 'ناراضی'), (3, 'متوسط'), (4, 'راضی'), (5, 'خیلی راضی')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
